name: Cowin Notifier
on: [push]
# schedule:
    # - cron: "*/5 * * * *"
jobs:
  cowin_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Run the script
        run: npm start
         