name: Cowin Notifier
on: [push]
# schedule:
# - cron: "*/5 * * * *"
jobs:
  cowin_notifier:
    runs-on: ubuntu-latest
    env:
      MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
      MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tor
        run: |
          sudo apt-get -y install tor
          sudo sh -c "echo 'ExitNodes 216.10.247.146' >> /etc/tor/torrc"
          sudo /etc/init.d/tor restart

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Run the script
        run: npm start
